name: Deploy Wiki

on:
  push:
    paths:
      - 'docs/source/**'
      - '.github/workflows/deploy_wiki.yml'
    branches:
      - develop

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Remove toctree
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: '.. toctree::\n    :includehidden:\n    :titlesonly:\n\n    User Guide'
        replace: ' '
        include: 'docs/source/**.rst'

    - name: Remove toc
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: '.. contents::\n   :depth: 2\n'
        replace: ' '
        include: 'docs/source/**.rst'

    - name: Remove headertable
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: '   .. rst-class:: headertable'
        replace: ' '
        include: 'docs/source/**.rst'

    - name: Remove footertable
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: '   .. rst-class:: footertable'
        replace: ' '
        include: 'docs/source/**.rst'

    - name: Remove table classes
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: '.. rst-class:: table-center\n\n       '
        replace: ' '
        include: 'docs/source/**.rst'

    - name: Remove figure classes
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: '       .. rst-class:: figure-tight\n\n '
        replace: ' '
        include: 'docs/source/**.rst'

    - name: Remove titles
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: '.. cssclass:: title\n\n   \|front-title\|\n\n.. cssclass:: title-sub\n\n   \|front-subtitle\|'
        replace: ' '
        include: 'docs/source/**.rst'

    - name: Fix image links
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: '../img/'
        replace: 'https://raw.githubusercontent.com/sfadschm/Raman-Live-Tool-Set/develop/docs/img/'
        include: 'docs/source/**.rst'

    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        WIKI_DIR: docs/source/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.YOUR_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
